name: Publish Docker image

on:
  push:
    branches:
      - master

env:
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t yp522/react-cloud:latest .

    - name: Login to Docker Hub
        run: |
        echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin

    - name: Publish Docker image
      run: docker push yp522/react-cloud:latest
